services:
  etl:
    build: .
    container_name: amazon_etl
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./etl:/app/etl
    networks:
      - amazon_network

  nyc_taxi_etl:
    build: .
    container_name: nyc_taxi_etl
    env_file:
      - .env
    volumes:
      - ./etl:/app/etl
    networks:
      - amazon_network
    command: ["python", "etl/nyc_taxi_etl.py"]

  grafana:
    image: grafana/grafana:latest
    container_name: amazon_grafana
    env_file:
      - .env
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    networks:
      - amazon_network

volumes:
  grafana_data:

networks:
  amazon_network:
    driver: bridge
